### PR TITLE
Sizing of profiles in profiles 

### PR DESCRIPTION
**Pull request by paigerube14**
Adding different size options into profiles

Dependent on PR in ci-profiles: [253](https://gitlab.cee.redhat.com/aosqe/ci-profiles/-/merge_requests/253)

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/profiles_update/22/console

### CODE REVIEW

**Comment by paigerube14** [comment]
Things should be working now, PTAL at my job [profiles_update](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/profiles_update/)

**Comment by qiliRedHat** [comment]
@paigerube14 
https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/4c368b3a2de16e35792713cf152632636610e41a/Jenkinsfile#L101

A copy past missing modification
sectionHeader: "Node Density Job Options" Should be "Network Perf Job Options"

**Pull request merged**
