### PR TITLE
Cleanup and fixes

### PR DESCRIPTION
**Pull request by memodi**
* performing cleanup to remove workload scripts. (still keeping some basic uperf scripts/configs for some small manual perf tests as an example)
* updating touchstone config per new ES data.
* adding ServiceMonitor config for FLP with Kafka.

### CODE REVIEW

**Review by nathan-weinberg — CHANGES_REQUESTED** [review]
Thanks for doing this cleanup @memodi - please remove the lines where `common.sh` is sourced in the `Jenkinsfile` and provide a run of the job just to ensure it is still functioning as expected - thanks to @paigerube14's suggestion in #215 you should be able to do this quite easily with your fork

**Comment by memodi** [comment]
> Thanks for doing this cleanup @memodi - please remove the lines where `common.sh` is sourced in the `Jenkinsfile` and provide a run of the job just to ensure it is still functioning as expected - thanks to @paigerube14's suggestion in #215 you should be able to do this quite easily with your fork

@nathan-weinberg - not sure how can I achieve that with my forked without having all changes here merged first to my forked repo,  could you guide?

**Comment by nathan-weinberg** [comment]
> > Thanks for doing this cleanup @memodi - please remove the lines where `common.sh` is sourced in the `Jenkinsfile` and provide a run of the job just to ensure it is still functioning as expected - thanks to @paigerube14's suggestion in #215 you should be able to do this quite easily with your fork
> 
> @nathan-weinberg - not sure how can I achieve that with my forked without having all changes here merged first to my forked repo, could you guide?

For sure, will send you a Slack message :+1:

**Comment by memodi** [comment]
thanks @nathan-weinberg , here's the success run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/cleanup/5/console

**Pull request merged**
