### PR TITLE
Adding concurrent builds performance testing workload jenkinsfile

### PR DESCRIPTION
**Pull request by paigerube14**
Adding in the concurrent builds workload that was just added to e2e-benchmark to the kube-burner job

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 Code change looks ok. But I saw the latest concurrent builds job on your branch failed for some cleanup issue. https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/concurrent-builds/. I guess it's because of https://github.com/cloud-bulldozer/e2e-benchmarking/pull/368?

**Comment by paigerube14** [comment]
Yes, think it was because of that PR I opened, will rerun today and ping on here

**Comment by paigerube14** [comment]
This code should be good to go: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/concurrent-builds/7/console

/assign @mffiedler  
/assign @qiliRedHat

**Pull request merged**
