### PR TITLE
Added ingress-perf workload functionality

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Resolves [NETOBSERV-1290](https://issues.redhat.com/browse/NETOBSERV-1290)

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
New test case created for this workload: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-70716

**Comment by paigerube14** [comment]
In general things here look good to me

**Comment by nathan-weinberg** [comment]
Tested successfully here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/489/

**Pull request merged**
