### PR TITLE
Adding vsphere support

### PR DESCRIPTION
**Pull request by paigerube14**
Adding creation of vsphere cluster as well as getting the proxy varaibles and adding them to the current ENV_VARS to be passed to future jobs

### CODE REVIEW

**Review by skordas — APPROVED** [review]
/lgtm

**Comment by paigerube14** [comment]
Also addigng env_vars to be passed to write-to-sheet properly, this will help vsphere executions

**Comment by qiliRedHat** [comment]
Tested with Paige's fork and branch, everything works well.
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/272
Flexy-install passed, scaleup failed but proxy are passed to cluster-workers-scaling job
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/273/console
Proxy are passed to max-services job
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/274/console
Proxy are passed to upgrade job

**Pull request merged**
