### PR TITLE
versioning for images

### PR DESCRIPTION
**Pull request by memodi**
With this PR, we wouldn't need to keep updating the versions of images with NOO versions, the source link used in code is kept to update by engineering.

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
@memodi can you test it with a job run?

**Comment by memodi** [comment]
> @memodi can you test it with a job run?

@nathan-weinberg - here you go: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/0.1.4/5/console thanks!

**Pull request merged**
