### PR TITLE
addressing broken Source installation and enhancement to deploy kafka

### PR DESCRIPTION
**Pull request by memodi**
addressing broken Source installation and enhancement to deploy kafka using script

/cc @Amoghrd @nathan-weinberg

### CODE REVIEW

**Comment by Amoghrd** [comment]
I had incorporated this change in the PR I had raised for removing patch statements https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/379

**Comment by Amoghrd** [comment]
I will just remove in that PR, its fine😅

**Comment by memodi** [comment]
> I had incorporated this change in the PR I had raised for removing patch statements #379

Oh, sorry about that, didn't know you had WIP PR 😄

**Comment by Amoghrd** [comment]
No worries😅

**Comment by nathan-weinberg** [comment]
Were these changes tested? Was there a success run?

**Pull request merged**
