### PR TITLE
Netobserv perf tests

### PR DESCRIPTION
**Pull request by memodi**
Adding Jenkins CI for netobserv.

### CODE REVIEW

**Comment by mffiedler** [comment]
@memodi @jechen0648   Since this is net new and just affects your team, we can merge and work on refinements as needed.   When you are happy with the state of the code, squash the commits to 1 final commit and I will merge.   I can also squash on merge but that gets your local repo out of sync with upstream.

**Comment by mffiedler** [comment]
I'll get Jean added as a collaborator.   In the meantime  I can approve once it is squashed.   cc:  @memodi

**Comment by memodi** [comment]
w

**Comment by memodi** [comment]
I think I have botched up this PR badly since it has been initially created and all the more since attempting to squash commits into one today. I am not sure if I can still squash if I already have a PR, but likely the user with write permissions on the repo can still squash commits on merge. 
@mffiedler - could you help me squash commits on this PR at the time of merge? 
/cc @nathan-weinberg

**Comment by mffiedler** [comment]
Squash merging.   Everyone needs to rebase or get a fresh copy of this branch.

**Pull request merged**
