### PR TITLE
Adding new grafana data source

### PR DESCRIPTION
**Pull request by paigerube14**
Trying to add in the new updated url's for kube-burner tests with grafana

### CODE REVIEW

**Comment by paigerube14** [comment]
Updated to change the name of the data source in grafana that we are using. Passing job here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/qe_es_grafana/5/

**Comment by nathan-weinberg** [comment]
LGTM, I'll let the others look before merging

**Comment by svetsa-rh** [comment]
@paigerube14 

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/qe_es_grafana/5/console

In the above output, following link is printed:
01-24 10:58:57.929  Tue Jan 24 15:45:26 UTC 2023 Indexing benchmark metadata to [https://ocp-qe:Perfscale22!@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/ripsaw-kube-burner](https://ocp-qe:Perfscale22!@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/ripsaw-kube-burner%1B[0m)

But when we try to access it, I get:
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ripsaw-kube-burner\u001B[0m]","resource.type":"index_or_alias","resource.id":"ripsaw-kube-burner\u001B[0m","index_uuid":"_na_","index":"ripsaw-kube-burner\u001B[0m"}],"type":"index_not_found_exception","reason":"no such index [ripsaw-kube-burner\u001B[0m]","resource.type":"index_or_alias","resource.id":"ripsaw-kube-burner\u001B[0m","index_uuid":"_na_","index":"ripsaw-kube-burner\u001B[0m"},"status":404}

And, in other place, following link is printed:
01-24 10:58:57.929  Tue Jan 24 15:45:39 UTC 2023 Running: touchstone_compare --database elasticsearch -url https://ocp-qe:Perfscale22!@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/ -u 92608e98-081b-4b1d-a30e-dba994cddb91 --config /tmp/cluster-density-92608e98-081b-4b1d-a30e-dba994cddb91/clusterVersion.json

and trying to access that link, gives:
{
  "name" : "51caaaba94dab120d3f63603e48b79c4",
  "cluster_name" : "463992265265:ocp-qe-perf-scale-test-elk",
  "cluster_uuid" : "FhKg5ybeQ_akevRSMLUB-Q",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2021-09-29T11:42:59.634166Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}


Are these links supposed to be accessible? If they are not, it's confusing to see the links but not being able to access them.

**Comment by paigerube14** [comment]
> @paigerube14
> 
> https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/qe_es_grafana/5/console
> 
> In the above output, following link is printed: 01-24 10:58:57.929 Tue Jan 24 15:45:26 UTC 2023 Indexing benchmark metadata to [https://ocp-qe:Perfscale22!@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/ripsaw-kube-burner](https://ocp-qe:Perfscale22!@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/ripsaw-kube-burner%1B%5B0m)
> 
> But when we try to access it, I get: {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [ripsaw-kube-burner\u001B[0m]","resource.type":"index_or_alias","resource.id":"ripsaw-kube-burner\u001B[0m","index_uuid":"_na_","index":"ripsaw-kube-burner\u001B[0m"}],"type":"index_not_found_exception","reason":"no such index [ripsaw-kube-burner\u001B[0m]","resource.type":"index_or_alias","resource.id":"ripsaw-kube-burner\u001B[0m","index_uuid":"_na_","index":"ripsaw-kube-burner\u001B[0m"},"status":404}
> 
> And, in other place, following link is printed: 01-24 10:58:57.929 Tue Jan 24 15:45:39 UTC 2023 Running: touchstone_compare --database elasticsearch -url https://ocp-qe:Perfscale22!@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/ -u 92608e98-081b-4b1d-a30e-dba994cddb91 --config /tmp/cluster-density-92608e98-081b-4b1d-a30e-dba994cddb91/clusterVersion.json
> 
> and trying to access that link, gives: { "name" : "51caaaba94dab120d3f63603e48b79c4", "cluster_name" : "463992265265:ocp-qe-perf-scale-test-elk", "cluster_uuid" : "FhKg5ybeQ_akevRSMLUB-Q", "version" : { "number" : "7.10.2", "build_flavor" : "oss", "build_type" : "tar", "build_hash" : "unknown", "build_date" : "2021-09-29T11:42:59.634166Z", "build_snapshot" : false, "lucene_version" : "8.7.0", "minimum_wire_compatibility_version" : "6.8.0", "minimum_index_compatibility_version" : "6.0.0-beta1" }, "tagline" : "You Know, for Search" }
> 
> Are these links supposed to be accessible? If they are not, it's confusing to see the links but not being able to access them.

That output is from the kube-burner job itself not this job. The link for elastic doesn't show anything without the kibana plugin url extension. I will send to you. 
This job updates are for being able to click on the link in the uuid column in the google sheet for cluster density and get a dashboard with data on it

**Pull request merged**
