### PR TITLE
Post results to es for ingress perf

### PR DESCRIPTION
**Pull request by paigerube14**
Post results for ingress perf to es wiht baselines

### CODE REVIEW

**Comment by svetsa-rh** [comment]
@paigerube14 Code looks good to me. Do we have a passing test run with this?

**Comment by paigerube14** [comment]
@svetsa-rh yes sorry forgot to put in here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/post-results-to-es/40/console

**Comment by qiliRedHat** [comment]
> https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/post-results-to-es/40/console
@paigerube14 Do you have Infra nodes in this cluster?
I noticed 'infra_node_count': '0', 'workload_node_count': '1', just want to check if the infra_node_count is correct.

**Comment by paigerube14** [comment]
@qiliRedHat no I don't think I did, I was just testing that posting to elastic was properly working for ingress-perf not that ingress ran properly

**Pull request merged**
