### PR TITLE
Adding scale down sizing

### PR DESCRIPTION
**Pull request by paigerube14**
Moved the code that waited for nodes to be ready into a resuable function. 

Adding code for when we are scaling down and to only match machinesets based on if they are worker types

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 
On my 4.11 AWS OVN cluster, there is no worker label, it seems not all worker machinesets has the worker label by default.
```
% oc get --no-headers machinesets -n openshift-machine-api -l machine.openshift.io/cluster-api-machine-role=worker
No resources found in openshift-machine-api namespace.

% oc get --no-headers machinesets -n openshift-machine-api --show-labels
qili-preserve-aws0518-pnkfq-worker-us-east-2a   1     1     1     1     6d6h   machine.openshift.io/cluster-api-cluster=qili-preserve-aws0518-pnkfq
qili-preserve-aws0518-pnkfq-worker-us-east-2b   1     1     1     1     6d6h   machine.openshift.io/cluster-api-cluster=qili-preserve-aws0518-pnkfq
qili-preserve-aws0518-pnkfq-worker-us-east-2c   1     1     1     1     6d6h   machine.openshift.io/cluster-api-cluster=qili-preserve-aws0518-pnkfq
```

**Review by skordas — APPROVED** [review]
/lgtm

**Comment by qiliRedHat** [comment]
> @paigerube14 On my 4.11 AWS OVN cluster, there is no worker label, it seems not all worker machinesets has the worker label by default.
> 
> ```
> % oc get --no-headers machinesets -n openshift-machine-api -l machine.openshift.io/cluster-api-machine-role=worker
> No resources found in openshift-machine-api namespace.
> 
> % oc get --no-headers machinesets -n openshift-machine-api --show-labels
> qili-preserve-aws0518-pnkfq-worker-us-east-2a   1     1     1     1     6d6h   machine.openshift.io/cluster-api-cluster=qili-preserve-aws0518-pnkfq
> qili-preserve-aws0518-pnkfq-worker-us-east-2b   1     1     1     1     6d6h   machine.openshift.io/cluster-api-cluster=qili-preserve-aws0518-pnkfq
> qili-preserve-aws0518-pnkfq-worker-us-east-2c   1     1     1     1     6d6h   machine.openshift.io/cluster-api-cluster=qili-preserve-aws0518-pnkfq
> ```

@paigerube14 Have you addressed this?

**Comment by paigerube14** [comment]
Successful scale-down job with infra and workload nodes: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-workers-scaling/139/console

**Comment by paigerube14** [comment]
PTAL @qiliRedHat @skordas @nathan-weinberg

**Pull request merged**
