### PR TITLE
Updates based on recent testing

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Changes made:
- Additions to Jenkins logging
- Fixed bug in `deploy_lokistack` where if `$WORKLOAD` wasn't set it would generate an invalid S3 bucket name
- Fixed bug where multiple artifacts caused Mr. Sandman to fail
- NOPE tool now collects Kafka broker data (I've updated ES/Kibana for this as well)
- Added `limits` block to `lokistack-1x-medium` CRD
- Added ability to configure NOO Controller Manger Pod Memory Limit
- Reorganized and enhanced deletion functions
- Updated noo main subscription channel 
- Renamed "release" CRDs to "upstream"

### CODE REVIEW

**Review by memodi — CHANGES_REQUESTED** [review]
@nathan-weinberg - looks good overall just minor suggestions. Could you add success run as well? thanks!

**Comment by nathan-weinberg** [comment]
@memodi here is a recent success run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/285/

And a cleanup run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/286/

**Pull request merged**
