### PR TITLE
Adding write with new variables

### PR DESCRIPTION
**Pull request by paigerube14**
After [Pr](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/408), need to update calls with new variables

### CODE REVIEW

**Comment by svetsa-rh** [comment]
@paigerube14 , do you have runs for this PR that you ran with your changes?

**Comment by paigerube14** [comment]
@svetsa-rh 
Please take a look at this lowest level test and I will make changes upward 

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/208/console

**Comment by paigerube14** [comment]
@svetsa-rh this is now ready for review. Most recent run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/215/

**Comment by svetsa-rh** [comment]
@paigerube14 I see https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/post-results-to-es/49/console as fail. Can you confirm more info is needed in post-results-to-es but not from kube-burner run so I can approve this PR.

**Pull request merged**
