### PR TITLE
Adding parallel runs of kraken,cerberus,upgrade(if set)

### PR DESCRIPTION
**Pull request by paigerube14**
Adding job to be able to run cerberus, kraken and an upgrade in parallel 

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/chaos_upgrade/41/console 
(failure only because I had to abort Cerberus b/c I gave too many iterations) 

Currently have to hard code number of iterations for cerberus to run. Each iteration (with the 3 second wait) takes between 7-10 seconds and an upgrade takes any where from 1.2 -3 hours. 
Note: For an upgrade that latest 1.2 hours I ran about 500 iterations in the same time

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 Besides upgrade test, running cerberus and/or kraken in parallel with some other jobs could be a general function. For example, running scale-ci with cerberus + kraken, running some regression test with cerberus + kraken. Now this job needs manually setting the number of cerberus and cerberus iterations, so it's loose coupled with the upgrade job. Shall we make cerberus + kraken (can choose to run a single one or both) a separate job, and other jobs like scale-ci, upgrade, regression can be added a checkbox and some parameters to call it in a stage and run in parallel with the origin stages.

**Comment by paigerube14** [comment]
> @paigerube14 Besides upgrade test, running cerberus and/or kraken in parallel with some other jobs could be a general function. For example, running scale-ci with cerberus + kraken, running some regression test with cerberus + kraken. Now this job needs manually setting the number of cerberus and kraken iterations, so it's loose coupled with the upgrade job. Shall we make cerberus + kraken (can choose to run a single one or both) a separate job, and other jobs like scale-ci, upgrade, regression can be added a checkbox and some parameters to call it in a stage and run in parallel with the origin stages.

Yes think that this type of functionality with calling all jobs in parallel can be added in the future but I was currently just trying to finish up work for the [chaos okr](https://issues.redhat.com/browse/OCPQE-12678) by end of year

There is going to have to be a lot of additional work to this job to make it work like loaded-upgrade (with all possible sub jobs and variables). 

Were you thinking that this job would have all the parallel calls or should we add a parallel option to each of the sub jobs you mentioned (kube-burner, regression, and upgrade)

**Comment by qiliRedHat** [comment]
@paigerube14 Got you! Let's merge this. The rest can be considered step by step next year.

**Review by qiliRedHat — APPROVED** [review]

**Pull request merged**
