### PR TITLE
router perf Kube with QE es server

### PR DESCRIPTION
**Pull request by qiliRedHat**
https://issues.redhat.com/browse/OCPQE-13633
Tested with https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/router-perf/19 -Passed

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 PTAL

**Comment by qiliRedHat** [comment]
Test passed but I had some Error, Paige said that's because there is no index for router-perf in kibana. She helped to added there. I will do one more test after I'm back from holiday
```
01-19 17:54:54.886  [1mThu Jan 19 09:54:54 UTC 2023 Running: touchstone_compare --database elasticsearch -url https://ocp-qe:****@search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com -u 69e0c5f3-5035-470d-881a-7e351efdd476 --config /tmp/router-perf-69e0c5f3-5035-470d-881a-7e351efdd476/mb-touchstone.json -o csv --output-file /home/jenkins/ws/workspace/i_qili-e2e-benchmark_router-perf/workloads/router-perf-v2/router-perf-69e0c5f3-5035-470d-881a-7e351efdd476.csv --rc 0[0m
01-19 17:54:55.953  2023-01-19 09:54:55,899 - touchstone - ERROR - Error: Issue capturing results from elasticsearch using config {'filter': {'test_type': 'http'}, 'buckets': ['routes', 'conn_per_targetroute', 'keepalive'], 'aggregations': {'requests_per_second': ['avg'], 'avg_latency': ['avg'], 'latency_95pctl': ['avg'], '200': ['avg'], '0': ['avg']}}
01-19 17:54:55.953  2023-01-19 09:54:55,947 - touchstone - ERROR - Error: Issue capturing results from elasticsearch using config {'filter': {'test_type': 'edge'}, 'buckets': ['routes', 'conn_per_targetroute', 'keepalive'], 'aggregations': {'requests_per_second': ['avg'], 'avg_latency': ['avg'], 'latency_95pctl': ['avg'], '200': ['avg'], '0': ['avg']}}
01-19 17:54:56.384  2023-01-19 09:54:55,998 - touchstone - ERROR - Error: Issue capturing results from elasticsearch using config {'filter': {'test_type': 'passthrough'}, 'buckets': ['routes', 'conn_per_targetroute', 'keepalive'], 'aggregations': {'requests_per_second': ['avg'], 'avg_latency': ['avg'], 'latency_95pctl': ['avg'], '200': ['avg'], '0': ['avg']}}
01-19 17:54:56.384  2023-01-19 09:54:56,047 - touchstone - ERROR - Error: Issue capturing results from elasticsearch using config {'filter': {'test_type': 'reencrypt'}, 'buckets': ['routes', 'conn_per_targetroute', 'keepalive'], 'aggregations': {'requests_per_second': ['avg'], 'avg_latency': ['avg'], 'latency_95pctl': ['avg'], '200': ['avg'], '0': ['avg']}} 
```

**Comment by nathan-weinberg** [comment]
@paigerube14 @qiliRedHat would y'all mind updating [this doc](https://docs.google.com/document/d/15BlwApK8nsYh_ym_Q8-7LUOpmx2ccvnUGqwdso6QtlM/edit#) with the ES changes you're making? We can rename it to more holistically represent it as a reference to the QE ES instance

**Comment by paigerube14** [comment]
> @paigerube14 @qiliRedHat would y'all mind updating [this doc](https://docs.google.com/document/d/15BlwApK8nsYh_ym_Q8-7LUOpmx2ccvnUGqwdso6QtlM/edit#) with the ES changes you're making? We can rename it to more holistically represent it as a reference to the QE ES instance

Will do!!

**Comment by qiliRedHat** [comment]
@paigerube14 Have you added the router-perf needed index to the es server? After you add it, I can do another test to see if everything is ok.

**Comment by qiliRedHat** [comment]
@paigerube14 I check the router-perf with old ES server, the Errors are still there. So this is not an issue with this pr. As long as the google sheet was generated, I think that means reading from the new ES's index was successful. Please add a final approve to this PR. The Errors is harmless but can be take care of later in e2e-benchmark side.

**Comment by qiliRedHat** [comment]
Test job - compare to existing UUID
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/router-perf/27/

**Pull request merged**
