### PR TITLE
Adding processor arch tracking to Perf automation

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Resolves [NETOBSERV-1006](https://issues.redhat.com/browse/NETOBSERV-1006)

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Arch Success: https://docs.google.com/spreadsheets/d/1ZPTunXgYYXBeOQqRXiQujUQRjzqPWmZ4j1CcMNfKJyQ/edit?usp=sharing

**Comment by nathan-weinberg** [comment]
eBPF pod-per-pod CPU stats: https://docs.google.com/spreadsheets/d/1XTSBByY3tsGnBzMLjKsGt1Yvv3GUBRbbOGbcofL7wgQ/edit?usp=sharing

**Comment by paigerube14** [comment]
looks good to me, will let someone on your team add proper comment

**Review by memodi — APPROVED** [review]
/lgtm

**Pull request merged**
