### PR TITLE
update loki manifests to use cluster default SC

### PR DESCRIPTION
**Pull request by memodi**
Resolves https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/260 partially
/cc @nathan-weinberg @mffiedler

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
LGTM @memodi - could we see a test job succeed just to verify? (only need install, no workload)

**Comment by memodi** [comment]
@nathan-weinberg - here's the success run: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/memodi-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/76/console

**Comment by memodi** [comment]
Tested prom. queries locally with command failing in [job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/85/consoleFull):

```
$ ./nope.py --starttime 1663183834 --endtime 1663184779 --jenkins-job scale-ci/e2e-benchmarking-multibranch-pipeline/kube-burner --jenkins-build 1254 --uuid 787906be-815c-4d3b-aa47-42fb15c3db49 --user-workloads --dump
INFO:root:Parsed Start Time: 03:30PM UTC on 09/14/2022
INFO:root:Parsed End Time:   03:46PM UTC on 09/14/2022
INFO:root:Step is:           10
INFO:root:Associating run with Jenkins job scale-ci/e2e-benchmarking-multibranch-pipeline/kube-burner build number 1254
INFO:root:UUID: 787906be-815c-4d3b-aa47-42fb15c3db49
INFO:root:YAML_FILE: netobserv_queries_ebpf.yaml
INFO:root:THANOS_URL: https://thanos-querier-openshift-monitoring.apps.nweinber-tbcontinued.qe.devcluster.openshift.com
INFO:root:TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6InFKYV9jRy1kVzRpRlNUal9DOW9KTzFsVGNJelpYQ0NDM1JZbTROdDlfU0kifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJvcGVuc2hpZnQtdXNlci13b3JrbG9hZC1tb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InByb21ldGhldXMtdXNlci13b3JrbG9hZC10b2tlbi1wN3M3NyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJwcm9tZXRoZXVzLXVzZXItd29ya2xvYWQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI3OTc0YTI0Yy1kN2ZmLTQzMmYtYjEwZC0yNmZjNmQ0YzIwODAiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6b3BlbnNoaWZ0LXVzZXItd29ya2xvYWQtbW9uaXRvcmluZzpwcm9tZXRoZXVzLXVzZXItd29ya2xvYWQifQ.usLAfJAO9831NJxS98t5-zMAaj_r9DDtHlITV6DmcrfLSqounmRt5_AtuC9MPJhyOOEVsWxjlMzs122fVEKhp1kGRLSMjN5qhTmd-iOTU4LjHxvUqu1FGQ7TMsv7bsm2QyuDAqv1JGhe68xikAFjnGDZqGMP5mdGsPOxYjgyS8rOMYJxHE4oIpc6pJQ1C2YHcizUSmnR4pUZn2GI6peJjmllN-H1BH9BZIv_h75wuX0LbrgbRvmzsqTij06cALIxDmHMLoaolf9pMGVN-kIJh8yYcG_f-ofxNAcWYTFsIvDk8iKLNBh3wY-9HKRWHyEo1Vt-DJ4C7ntBhvOZ-FASzojgBPZbQz3lfE7UjCbRJZ_LkwmtH4aiyvb-ReunRpocacbCqcDKaCflErW32ykchhc_Z4mfPse2bP0UHh_XtZd3txfaEktivASHzX-uEECeueIJP6bCeDllFnhUpepdk7k6zssCF1J7RI0U32_mGZA286IafPsXj5aFmFlhcY9bP7gQpmu_pB-5kN4Dd8ud1Bmxp2V-d5UZulJFU-F-rLAgKazaiqLXl4AdX5k2JAmPCe0PWcYk-8POh8JbJcwpDrIXH2RLHI9_x4mMThn7fzwoPXWMp24ZQzH1ha9ksVDvkigSd5aha1ejZnFACIfC5c3sjwYkKzydYY--ZsS_dqQ
INFO:root:Data will be dumped locally to /Users/memodi/workspaces/repos/ocp-qe-perfscale-ci/data
INFO:root:Data captured successfully
INFO:root:Data written to /Users/memodi/workspaces/repos/ocp-qe-perfscale-ci/data/data_2022-09-15_11-22-42.json
```

**Pull request merged**
