### PR TITLE
Adding cerberus and cleanup checks to kube-burner

### PR DESCRIPTION
**Pull request by paigerube14**
Adding cerberus check and cleanup options in kube-burner job

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 Please past the job if you have tested the change.

**Comment by paigerube14** [comment]
@qiliRedHat https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner/37/console

**Comment by nathan-weinberg** [comment]
Looks good to me, but will let @qiliRedHat give final approval

**Pull request merged**
