### PR TITLE
Getting machineset using additional label flag to ignore 'infra' nodes.

### PR DESCRIPTION
**Pull request by skordas**
$title
Please check issue https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/145 for more information.

### CODE REVIEW

**Comment by skordas** [comment]
@paigerube14 ptal

**Comment by paigerube14** [comment]
@skordas 
I did a quick test on one of Sharada's clusters and using the new label you had added I still get the whole list back. Looking at the labels.  I do not see any easy way to figure out the machinesets that are workers vs infra/workload nodes. Think we need to keep looking 

```
% oc get --no-headers machinesets -A -l machine.openshift.io/cluster-api-cluster
openshift-machine-api   infra-us-east-1a                               1     1                 2m13s
openshift-machine-api   infra-us-east-1b                               1     1                 2m13s
openshift-machine-api   infra-us-east-1c                               1     1                 2m13s
openshift-machine-api   svetsa-9323-baseline-5tx7k-worker-us-east-1a   24    24    24    24    43m
openshift-machine-api   svetsa-9323-baseline-5tx7k-worker-us-east-1b   24    24    24    24    43m
openshift-machine-api   svetsa-9323-baseline-5tx7k-worker-us-east-1c   24    24    24    24    43m
openshift-machine-api   svetsa-9323-baseline-5tx7k-worker-us-east-1d   24    24    24    24    43m
openshift-machine-api   svetsa-9323-baseline-5tx7k-worker-us-east-1f   24    24    24    24    43m
openshift-machine-api   workload-us-east-1a                            1     1                 2m12s
```

**Comment by qiliRedHat** [comment]
Tested with job https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/cluster-workers-scaling/714/console, infra machinesets are not scaled.
```
% oc get machinesets -A
NAMESPACE               NAME                               DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-machine-api   qili-az-d9sqx-infra-centralus1     1         1         1       1           153m
openshift-machine-api   qili-az-d9sqx-infra-centralus2     1         1         1       1           153m
openshift-machine-api   qili-az-d9sqx-infra-centralus3     1         1         1       1           153m
openshift-machine-api   qili-az-d9sqx-worker-centralus1    2         2                             4h31m
openshift-machine-api   qili-az-d9sqx-worker-centralus2    0         0                             4h31m
openshift-machine-api   qili-az-d9sqx-worker-centralus3    0         0                             4h31m
openshift-machine-api   qili-az-d9sqx-workload-centralus   1         1         1       1           153m
```

**Comment by qiliRedHat** [comment]
@skordas @paigerube14 Not working on GCP, I opened https://github.com/openshift-qe/ocp-qe-perfscale-ci/issues/153 to investigate.

**Pull request merged**
