### PR TITLE
Updating Prometheus queries for Dittybopper and NOPE

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Among other things

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Downstream Install/Metrics verified here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/310/

**Comment by nathan-weinberg** [comment]
OperatorHub Install verified here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/311

**Comment by nathan-weinberg** [comment]
Source installation failed due to [NETOBSERV-775](https://issues.redhat.com/browse/NETOBSERV-775) (unrelated to this PR): https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/312/

**Comment by nathan-weinberg** [comment]
Reorg'd files as well, retested:
Downstream: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/313/
OperatorHub: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/315/

**Comment by nathan-weinberg** [comment]
Source Installation Fix: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/316/

**Review by memodi — APPROVED** [review]
/lgtm

**Comment by Amoghrd** [comment]
LGTM

**Pull request merged**
