### PR TITLE
Add Nutanix INFRA and WORKLOAD

### PR DESCRIPTION
**Pull request by qiliRedHat**
Add automation for 
https://issues.redhat.com/browse/OCPQE-13602 Add INFRA and WORKLOAD automation for Nuntanix

### CODE REVIEW

**Comment by qiliRedHat** [comment]
Tested with Jenkins job on my own fork
First test failed, the INFRA machine stuck in Provisioning for a long time, I suspect the cpu memory is too big for Nutanix. https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/cluster-post-config/51/console
I will try with a smaller size.

**Comment by qiliRedHat** [comment]
Test passed job
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/cluster-post-config/55/console
with ENV
```
OPENSHIFT_INFRA_NODE_INSTANCE_VCPU=16
OPENSHIFT_INFRA_NODE_INSTANCE_MEMORYMB=65536
OPENSHIFT_INFRA_NODE_INSTANCE_MEMORYSIZE=64Gi
OPENSHIFT_WORKLOAD_NODE_INSTANCE_VCPU=8
OPENSHIFT_WORKLOAD_NODE_INSTANCE_MEMORYMB=32768
OPENSHIFT_WORKLOAD_NODE_INSTANCE_MEMORYSIZE=32Gi
```
Manual check is good
```
 % oc get machinesets -A
NAMESPACE               NAME                          DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-machine-api   qili-nut-big-np8jj-infra      3         3         3       3           6m48s
openshift-machine-api   qili-nut-big-np8jj-worker     2         2         2       2           3h40m
openshift-machine-api   qili-nut-big-np8jj-workload   1         1         1       1           6m47s

% oc get node| grep infra
qili-nut-big-np8jj-infra-n7xzx      Ready    infra                  2m55s   v1.25.4+77bec7a
qili-nut-big-np8jj-infra-p58sm      Ready    infra                  3m40s   v1.25.4+77bec7a
qili-nut-big-np8jj-infra-tzgdc      Ready    infra                  3m7s    v1.25.4+77bec7a


% oc get po -owide -n openshift-ingress
NAME                              READY   STATUS    RESTARTS   AGE     IP             NODE                             NOMINATED NODE   READINESS GATES
router-default-69b759bcc4-djght   1/1     Running   0          10m     10.0.132.73    qili-nut-big-np8jj-infra-tzgdc   <none>           <none>
router-default-69b759bcc4-v4trk   1/1     Running   0          7m11s   10.0.132.135   qili-nut-big-np8jj-infra-p58sm   <none>           <none>

% oc get po -owide -n openshift-monitoring | grep infra      
alertmanager-main-0                                      6/6     Running   1 (3m57s ago)   7m40s   10.129.6.7     qili-nut-big-np8jj-infra-p58sm      <none>           <none>
alertmanager-main-1                                      6/6     Running   1 (3m26s ago)   10m     10.130.6.9     qili-nut-big-np8jj-infra-tzgdc      <none>           <none>
kube-state-metrics-64fd64448d-mpxw4                      3/3     Running   0               10m     10.129.6.11    qili-nut-big-np8jj-infra-p58sm      <none>           <none>
node-exporter-bm4wb                                      2/2     Running   0               4m2s    10.0.132.73    qili-nut-big-np8jj-infra-tzgdc      <none>           <none>
node-exporter-k4sqc                                      2/2     Running   0               4m35s   10.0.132.135   qili-nut-big-np8jj-infra-p58sm      <none>           <none>
node-exporter-wtwlf                                      2/2     Running   0               3m50s   10.0.132.148   qili-nut-big-np8jj-infra-n7xzx      <none>           <none>
prometheus-adapter-668dcf9c56-7h5zp                      1/1     Running   0               8m      10.129.6.5     qili-nut-big-np8jj-infra-p58sm      <none>           <none>
prometheus-adapter-668dcf9c56-pqzzf                      1/1     Running   0               10m     10.130.6.7     qili-nut-big-np8jj-infra-tzgdc      <none>           <none>
prometheus-k8s-0                                         6/6     Running   0               7m40s   10.129.6.9     qili-nut-big-np8jj-infra-p58sm      <none>           <none>
prometheus-k8s-1                                         6/6     Running   0               10m     10.130.6.5     qili-nut-big-np8jj-infra-tzgdc      <none>           <none>
prometheus-operator-58d6749947-lhhw7                     2/2     Running   0               10m     10.129.6.8     qili-nut-big-np8jj-infra-p58sm      <none>           <none>
prometheus-operator-admission-webhook-66b47499bd-dvmjg   1/1     Running   0               10m     10.130.6.6     qili-nut-big-np8jj-infra-tzgdc      <none>           <none>
prometheus-operator-admission-webhook-66b47499bd-tkk9l   1/1     Running   0               7m40s   10.129.6.6     qili-nut-big-np8jj-infra-p58sm      <none>           <none>
```

**Comment by qiliRedHat** [comment]
Test on cluster with pvc PASSed

qili-nut-pvc
Server Version: 4.13.0-0.nightly-2023-01-17-152326
[https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Flexy-install/172541/]
private-templates/functionality-testing/aos-4_12/ipi-on-nutanix//versioned-installer-fips-ovn-csi_pvc-ci
master_num_memory: 32768
worker_num_memory: 16384
networkType: "OVNKubernetes"

[https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/cluster-post-config/66] 
```
OPENSHIFT_INFRA_NODE_INSTANCE_VCPU=16
OPENSHIFT_INFRA_NODE_INSTANCE_MEMORYSIZE=64Gi
OPENSHIFT_WORKLOAD_NODE_INSTANCE_VCPU=16
OPENSHIFT_WORKLOAD_NODE_INSTANCE_MEMORYSIZE=64Gi
OPENSHIFT_PROMETHEUS_RETENTION_PERIOD=15d
OPENSHIFT_PROMETHEUS_STORAGE_SIZE=50Gi
OPENSHIFT_ALERTMANAGER_STORAGE_SIZE=1Gi
```
Manual check:
```
% oc get machinesets -A
NAMESPACE               NAME                          DESIRED   CURRENT   READY   AVAILABLE   AGE
openshift-machine-api   qili-nut-pvc-n8bsp-infra      3         3         3       3           7m41s
openshift-machine-api   qili-nut-pvc-n8bsp-worker     2         2         2       2           5h54m
openshift-machine-api   qili-nut-pvc-n8bsp-workload   1         1         1       1           7m40s

% oc get po -owide -n openshift-ingress
NAME                              READY   STATUS    RESTARTS   AGE     IP             NODE                             NOMINATED NODE   READINESS GATES
router-default-545f8c7965-7hhtk   1/1     Running   0          2m33s   10.0.132.73    qili-nut-pvc-n8bsp-infra-fh45q   <none>           <none>
router-default-545f8c7965-8vjc8   1/1     Running   0          15m     10.0.132.217   qili-nut-pvc-n8bsp-infra-l4qmj   <none>           <none>

% oc get po -owide -n openshift-monitoring | grep -v exporter
NAME                                                     READY   STATUS    RESTARTS        AGE     IP             NODE                                NOMINATED NODE   READINESS GATES
alertmanager-main-0                                      6/6     Running   1 (2m38s ago)   2m51s   10.129.8.8     qili-nut-pvc-n8bsp-infra-t6btr      <none>           <none>
alertmanager-main-1                                      6/6     Running   1 (4m27s ago)   16m     10.128.8.10    qili-nut-pvc-n8bsp-infra-l4qmj      <none>           <none>
cluster-monitoring-operator-57dc86858f-qsd6m             2/2     Running   0               5h14m   10.130.0.45    qili-nut-pvc-n8bsp-master-0         <none>           <none>
kube-state-metrics-6b44cd5bfb-52z4h                      3/3     Running   0               16m     10.128.8.9     qili-nut-pvc-n8bsp-infra-l4qmj      <none>           <none>
openshift-state-metrics-86586655c5-kqs87                 3/3     Running   0               5h22m   10.131.0.13    qili-nut-pvc-n8bsp-worker-jtvnl     <none>           <none>
prometheus-adapter-5b8c6bbbbd-6545m                      1/1     Running   0               2m21s   10.130.8.9     qili-nut-pvc-n8bsp-infra-fh45q      <none>           <none>
prometheus-adapter-5b8c6bbbbd-n6v42                      1/1     Running   0               2m21s   10.129.8.9     qili-nut-pvc-n8bsp-infra-t6btr      <none>           <none>
prometheus-k8s-0                                         6/6     Running   0               2m52s   10.130.8.8     qili-nut-pvc-n8bsp-infra-fh45q      <none>           <none>
prometheus-k8s-1                                         6/6     Running   0               16m     10.128.8.5     qili-nut-pvc-n8bsp-infra-l4qmj      <none>           <none>
prometheus-operator-8f4cd8977-w4krc                      2/2     Running   0               16m     10.128.8.7     qili-nut-pvc-n8bsp-infra-l4qmj      <none>           <none>
prometheus-operator-admission-webhook-64d547c57c-b9ncp   1/1     Running   0               16m     10.128.8.8     qili-nut-pvc-n8bsp-infra-l4qmj      <none>           <none>
prometheus-operator-admission-webhook-64d547c57c-m54pl   1/1     Running   0               3m2s    10.129.8.7     qili-nut-pvc-n8bsp-infra-t6btr      <none>           <none>
telemeter-client-8574dd76cb-2g2b5                        3/3     Running   0               5h22m   10.131.0.15    qili-nut-pvc-n8bsp-worker-jtvnl     <none>           <none>
thanos-querier-9dfdbb949-247md                           6/6     Running   0               5h28m   10.131.0.10    qili-nut-pvc-n8bsp-worker-jtvnl     <none>           <none>
thanos-querier-9dfdbb949-w4blz                           6/6     Running   0               5h22m   10.128.2.8     qili-nut-pvc-n8bsp-worker-nffqf     <none>           <none>{code}
```
From web console all infra and workload vms are running and with correct CPU and memory config, no warnings.
|qili-nut-pvc-n8bsp-infra-fh45q|16|64 GiB|

The memory usage of Development-LTS is 54.8%

**Comment by qiliRedHat** [comment]
NOTE:
The quota limitation on Nutanix can not support 40 worker nodes + INFRA and WORKLOAD nodes. So we can either apply to increase the resource on Nutanix. Or with the current resource, use a smaller number of worker nodes.

**Comment by svetsa-rh** [comment]
@qiliRedHat 
I see that https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/e9fb839111a6fbfc95412a0849a9fb12ae49d052/infra-node-machineset-nutanix.yaml and https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/e9fb839111a6fbfc95412a0849a9fb12ae49d052/workload-node-machineset-nutanix.yaml only specify 4vCPU and 16 GB.

 machine.openshift.io/memoryMb: "16384"
 machine.openshift.io/vCPU: "4"

But the machine instances are requested to be 4x larger, https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/e9fb839111a6fbfc95412a0849a9fb12ae49d052/Jenkinsfile

               OPENSHIFT_INFRA_NODE_INSTANCE_VCPU=16<br>
               OPENSHIFT_INFRA_NODE_INSTANCE_MEMORYSIZE=64Gi<br>
               OPENSHIFT_WORKLOAD_NODE_INSTANCE_VCPU=16<br>
               OPENSHIFT_WORKLOAD_NODE_INSTANCE_MEMORYSIZE=64Gi<br>

Each instance hosts just one node right? Why the difference?

**Comment by qiliRedHat** [comment]
@svetsa-rh 
The Annotations machine.openshift.io/memoryMb: "16384"
machine.openshift.io/vCPU: "4" are for the cluster autoscaler, worker nodes have the same settings. Check this document for detail https://docs.openshift.com/container-platform/4.11/machine_management/creating-infrastructure-machinesets.html#machineset-yaml-nutanix_creating-infrastructure-machinesets. 

The actual cpu memory settings for the infra machines are under providerSpec:
memorySize: ${OPENSHIFT_INFRA_NODE_INSTANCE_MEMORYSIZE}
vcpuSockets: ${OPENSHIFT_INFRA_NODE_INSTANCE_VCPU}

**Comment by qiliRedHat** [comment]
@svetsa-rh Please help to review again, if there is no other comment, we can merge it.

**Pull request merged**
