### PR TITLE
Updated NetObserv Touchstone config files and relevant automation

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Related to https://github.com/cloud-bulldozer/e2e-benchmarking/pull/550

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Tested here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/87/

**Comment by nathan-weinberg** [comment]
Generated spreadsheet: https://docs.google.com/spreadsheets/d/187HR7-ZhodnOdlVQXfQUZ1QM8psTWgzsh4Khj5CeqlM/edit#gid=1250991337

**Comment by memodi** [comment]
@nathan-weinberg - how would this work if this gets merged prior to https://github.com/cloud-bulldozer/e2e-benchmarking/pull/550 ?

**Comment by nathan-weinberg** [comment]
@memodi it won't, which is why we are going to merge the other one first :) i'll ping you in the relevant slack thread

**Comment by nathan-weinberg** [comment]
@memodi it won't, which is why we are going to merge the other one first :) i'll ping you in the relevant slack thread

**Comment by memodi** [comment]
> @memodi it won't, which is why we are going to merge the other one first :) i'll ping you in the relevant slack thread

that's what I thought, but now I am confused since you attached success run and I don't see you use your forked e2e-benchmarking repo , so how did it pass? 😁

**Comment by nathan-weinberg** [comment]
> > @memodi it won't, which is why we are going to merge the other one first :) i'll ping you in the relevant slack thread
> 
> that's what I thought, but now I am confused since you attached success run and I don't see you use your forked e2e-benchmarking repo , so how did it pass? grin

Ah you want to know the secret sauce ;) I had a temp commit that change the path of the `e2e-benchmarking` repo from `cloud-bulldozer/master` to `nathan-weinberg/compare` so I could see if this behavior would work in our pipeline before merging into that repo - removed it once I verified that

**Comment by memodi** [comment]
> Ah you want to know the secret sauce ;) I had a temp commit that changed the path of the `e2e-benchmarking` repo from `cloud-bulldozer/master` to `nathan-weinberg/compare` in the `Jenkinsfile` so I could see if this behavior would work in our pipeline before merging into that repo - removed it once I verified that

interesting, I see it now: https://github.com/nathan-weinberg/ocp-qe-perfscale-ci/commit/2196bde8407881628fd5c7a0c21bb34274c40058

**Pull request merged**
