### PR TITLE
Altered index strategy in NOPE and Touchstone

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Resolves [NETOBSERV-620](https://issues.redhat.com/browse/NETOBSERV-620)

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Tested with prod index pattern:
image

**Comment by nathan-weinberg** [comment]
- Tested E2E with our test index here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/schemin/17/
- `iso_timestamp` field automatically being parsed by ES as a `date` type, visible here: https://search-ocp-qe-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com/
- Grafana (Dittybopper) recognized our test ES index pattern as a valid datasource, using `iso_timestamp` as the timestamp field
    - I've reached out to PerfScale Dev to confirm the same for their long-lived Grafana instance

@memodi @paigerube14 anything else we want to do before I open this for review?

**Comment by memodi** [comment]
> @memodi @paigerube14 anything else we want to do before I open this for review?

@nathan-weinberg I think should be good for this PR, we'll likely have to update touchstone to add more metrics soon that I am currently working on.

**Comment by paigerube14** [comment]
Looks good to me

**Comment by nathan-weinberg** [comment]
> > @memodi @paigerube14 anything else we want to do before I open this for review?
> 
> @nathan-weinberg I think should be good for this PR, we'll likely have to update touchstone to add more metrics soon that I am currently working on.

Sounds good, just need to make sure we update it both here and in https://github.com/cloud-bulldozer/e2e-benchmarking/pull/498 (if we only want to maintain one copy, we could just maintain the e2e-benchmakring version and remove this one)

**Comment by nathan-weinberg** [comment]
> > Sounds good, just need to make sure we update it both here and in [cloud-bulldozer/e2e-benchmarking#498](https://github.com/cloud-bulldozer/e2e-benchmarking/pull/498) (if we only want to maintain one copy, we could just maintain the e2e-benchmakring version and remove this one)
> 
> Could you elaborate what is the motivation/advantages of having our touchstone config in e2e-benchmarking? I know we discussed it a bit but wasn't quite clear to me what is that we'll gain having it there?

Will message you on Slack about this

**Pull request merged**
