### PR TITLE
Automation changes now that eBPF will be default collector agent

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Did some minor cleanup on a few things as well

### CODE REVIEW

**Comment by memodi** [comment]
@nathan-weinberg -  thanks, changes looks good to me, could you add success job link with ebpf collector agent?

**Comment by nathan-weinberg** [comment]
@memodi here is the job https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/netobserv-perf-tests/49/

**Pull request merged**
