### PR TITLE
Adding if statement for blank release

### PR DESCRIPTION
**Pull request by paigerube14**
Couldn't find release in file https://github.com/openshift/release/blob/master/ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__write_jobs_to_gsheet.yaml that is being looked at in the job

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 I checked the new tab you generated yesterday with the above pr rehearse. 'hypershift' Cloud Type in the past now appear as 'rosa'. I left comments for you in the [google sheet](https://docs.google.com/spreadsheets/d/1TM73n4Y6zKRQjvCX8zFM0LwYxChdsncTEGPHpdsS9Ig/edit#gid=2103328750). Would you help to check what was changed there in the jobs that caused the difference? You can do it in the separate pr if you like

**Comment by qiliRedHat** [comment]
@paigerube14 we can address the 'hypershift' issue in an other pr. We can merge this fix for blank release first if you prefer.

**Comment by paigerube14** [comment]
@qiliRedHat yes would prefer if we could merge this in first. Especially since I didn't change anything to do with that area

**Comment by afcollins** [comment]
Not understanding this failure, but I tested the change locally and it LGTM

**Pull request merged**
