### PR TITLE
Adding scale up and down back in

### PR DESCRIPTION
**Pull request by paigerube14**
Based on Qiujie's comment [here](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/103#issuecomment-1070509912), adding back the scaleup and down into this job to make running more flexible. 

Just won't pass the parameters from the loaded-upgrade so we don't run into double scaling isuses

### CODE REVIEW

**Review by skordas — APPROVED** [review]
/lgtm

**Comment by qiliRedHat** [comment]
@paigerube14 Thanks for adding them back. Code looks good but why I didn't see this in the Jenkins sandbox https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/kube-burner-2/?

**Comment by paigerube14** [comment]
When you make updates to the parameters you have to run a build  for Jenkins to see the parameters have updated and then they would be at the build with parameters the next time. I usually just give blank build number so it doesn't actually run the test at all

**Pull request merged**
