### PR TITLE
Router perf w2f

### PR DESCRIPTION
**Pull request by qiliRedHat**
https://issues.redhat.com/browse/OCPQE-9394
Add WRITE_TO_FILE check box to router-perf scale-ci job.
Tested with https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/router-perf-w2f/20
Edit some description and default value, refine the layout.

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 PTAL

**Comment by paigerube14** [comment]
@qiliRedHat I had opened the exact same PR yesterday (https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/110/). We can use this one though to get this code merged.

**Comment by paigerube14** [comment]
@qiliRedHat can you squash your commits when you get a chance

**Comment by qiliRedHat** [comment]
@paigerube14 Aha, I missed your PR (https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/110). I rebased but failed on pushing back. Curious about the bot's behavior again - bot added the lgtm label.

**Comment by paigerube14** [comment]
I had added lgtm before I noticed it had 2 commits, but the bot didn't understand deleting comments.

**Comment by qiliRedHat** [comment]
Aha! Paige, I saw this, will test the bot next time ;)

> If the code changes look good to them, a reviewer types /lgtm in a PR comment or review; if they change their mind, they /lgtm cancel

**Pull request merged**
