### PR TITLE
Adding rhel8 oc

### PR DESCRIPTION
**Pull request by paigerube14**
CC: @jtaleric

### CODE REVIEW

**Review by jtaleric — APPROVED** [review]
/lgtm

**Comment by qiliRedHat** [comment]
@paigerube14 The test job failed
```
INFO[2024-07-10T01:19:55Z] Running step loaded-upgrade-415to416-24nodes-openshift-qe-workers-infra-workload. 
INFO[2024-07-10T01:20:32Z] Logs for container test in pod loaded-upgrade-415to416-24nodes-openshift-qe-workers-infra-workload: 
INFO[2024-07-10T01:20:32Z] oc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib/x86_[64](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-qe_ocp-qe-perfscale-ci/617/pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes/1810829337155342336#1:build-log.txt%3A64)-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by oc)
```

**Comment by qiliRedHat** [comment]
discussed with Paige, the new code passed on local test, the pj-rehearse job may failed because of the old prow base image. Try to merge this pr to see if it can fix the issue, given all our ci jobs are failing now.

**Comment by qiliRedHat** [comment]
/override ci/prow/ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

**Comment by qiliRedHat** [comment]
/override ci/prow/ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

**Comment by paigerube14** [comment]
/override ci/prow/ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

**Pull request merged**
