### PR TITLE
add write_nightly_longrun_results

### PR DESCRIPTION
**Pull request by qiliRedHat**

### CODE REVIEW

**Comment by qiliRedHat** [comment]
@paigerube14 
There is an insight operator issue in long running test now. 
`oc get clusterversion -o json` got the following
```
                    {
                        "lastTransitionTime": "2022-08-17T09:33:28Z",
                        "message": "Error while reconciling 4.12.0-0.nightly-2022-08-12-053438: the cluster operator insights is not available",
                        "reason": "ClusterOperatorNotAvailable",
                        "status": "False",
                        "type": "Progressing"
                    },
``` 
So the below code got cluster verison as 'available', and [job](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/qili-e2e-benchmark/job/write-scale-ci-results/17/console) failed
https://github.com/openshift-qe/ocp-qe-perfscale-ci/blob/968789f47476206a911a828e5e8c7c0ff0325029/write_to_sheet/write_helper.py#L70-L78

I don't quite understand why we get the version from 'Progressing' conditions? 

In a 'good' cluster, the 'Progressing' condition looks like below
```
                    {
                        "lastTransitionTime": "2022-08-17T09:33:28Z",
                        "message": "Error while reconciling 4.12.0-0.nightly-2022-08-12-053438: the cluster operator insights is not available",
                        "reason": "ClusterOperatorNotAvailable",
                        "status": "False",
                        "type": "Progressing"
                    },
```

**Comment by paigerube14** [comment]
@qiliRedHat I think I had looked at progressing to get the version we are progressing to during an upgrade. 
This code looks good to me though. If you want to try to fix it to do the available version number, or I can. Either way works for me

**Comment by qiliRedHat** [comment]
@paigerube14 PTAL again [updage get_oc_version to get version from oc cli output](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/231/commits/6f523eee60a592387dacd02e5255e6318d2cbea9)

**Pull request merged**
