### PR TITLE
new variables for write - loaded upgrade

### PR DESCRIPTION
**Pull request by paigerube14**
After [Pr](https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/408), need to update calls with new variables

### CODE REVIEW

**Comment by svetsa-rh** [comment]
@paigerube14 , do you have runs for this PR that you ran with your changes?

**Comment by paigerube14** [comment]
@svetsa-rh trying some now. Realized I used a jenkins keyword in some places so having to update all refernces of that. Will add comment when I fix

**Comment by svetsa-rh** [comment]
@paigerube14 If these changes are part of a bigger change and you need these interim changes, let me know so you can continue to have your env for remaining work. 
Changes themselves look fine but before approving thought of checking the run, if you had one.

**Comment by paigerube14** [comment]
@svetsa-rh this job is good to review. I found issues in the write to sheet code that I opened pr: https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/415

This passed the proper parameters to the job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/loaded-upgrade/370/console

**Pull request merged**
