### PR TITLE
Adding correct result to not get null error

### PR DESCRIPTION
**Pull request by paigerube14**
Fixing incorrect variable if scale-ci job fails; found by Nathan so adding him to list of reviewers

@mffiedler do I need to also add him in the PROW owners list or is just here ok?

### CODE REVIEW

**Comment by mffiedler** [comment]
Just here should be ok for now.  @nathan-weinberg you need to request membership to the openshift-qe org.

**Review by nathan-weinberg — APPROVED** [review]
Looks like my review permissions are working :+1:

**Pull request merged**
