### PR TITLE
update prow ci add infra/workload and move pods script to replace old script

### PR DESCRIPTION
**Pull request by liqcui**
To support vsphere8,  we can use the same script of prow ci to add infra/workload and move monitoring/registry/ingress pods script. 

We don't remove old script, just adding new script. 

The Jenkins job is https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/liqcui-e2e-benchmarking-multibranch-pipeline/job/cluster-post-config/195/console

### CODE REVIEW

**Comment by paigerube14** [comment]
@liqcui once we add these scripts it would be good if we could maybe update the prow job to clone this repo/branch code. So we would be able to know it has the same code and don't get prow and jenkins out of sync.

**Comment by liqcui** [comment]
> @liqcui once we add these scripts it would be good if we could maybe update the prow job to clone this repo/branch code. So we would be able to know it has the same code and don't get prow and jenkins out of sync.

I will update prow ci later and make it consistency

**Pull request merged**
