### PR TITLE
Added router-perf output to archived artifacts

### PR DESCRIPTION
**Pull request by nathan-weinberg**
Similar to https://github.com/openshift-qe/ocp-qe-perfscale-ci/pull/235

### CODE REVIEW

**Comment by nathan-weinberg** [comment]
Running test on this now, will share results once they are available

**Comment by nathan-weinberg** [comment]
Testing here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/nweinber-e2e-benchmarking-multibranch-pipeline/job/router-perf/10/

**Review by memodi — APPROVED** [review]

**Pull request merged**
