### PR TITLE
Ready test check for infra and workload nodes 

### PR DESCRIPTION
**Pull request by paigerube14**
Adding in check for ready status when adding infra and workload nodes

### CODE REVIEW

**Review by memodi — APPROVED** [review]

**Comment by paigerube14** [comment]
@qiliRedHat when I was doing my own testing without the extra \ in \\n jenkins was throwing an error and was not able to properly get the output of the command

```
05-23 15:36:48.083  ++ oc get nodes -l node-role.kubernetes.io/infra= --no-headers -o 'jsonpath={range .items[*]}{.status.conditions[?(@.type=="Ready")].status}{"
05-23 15:36:48.083  "}{end}'
05-23 15:36:48.083  ++ grep True
05-23 15:36:48.083  ++ xargs
05-23 15:36:48.083  ++ wc -l
05-23 15:36:48.394  error: error parsing jsonpath {range .items[*]}{.status.conditions[?(@.type=="Ready")].status}{"
05-23 15:36:48.394  "}{end}, unterminated quoted string
```
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-post-config/63/console


it passed here with the infra and workload machinesets already being created, but the checks themselves passed (that was failing above)
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cluster-post-config/64/console

**Comment by paigerube14** [comment]
@qiliRedHat I updated this PR to take out the label of infra and workload nodes to not also have 'worker'

**Comment by paigerube14** [comment]
@qiliRedHat I added back in the oc label lines, this takes the nodes that are infra/workload nodes and takes off the worker label so things don't get scheduled to them


```
NAME                                 STATUS     ROLES             AGE     VERSION
prubenda-osp4-c9666-infra-792hx      Ready      infra,worker      82s     v1.23.3+ad897c4
prubenda-osp4-c9666-infra-9z827      Ready      infra,worker      45s     v1.23.3+ad897c4
prubenda-osp4-c9666-infra-q5szq      NotReady   infra,worker      29s     v1.23.3+ad897c4
prubenda-osp4-c9666-master-0         Ready      master            4h6m    v1.23.3+ad897c4
prubenda-osp4-c9666-master-1         Ready      master            4h6m    v1.23.3+ad897c4
prubenda-osp4-c9666-master-2         Ready      master            4h6m    v1.23.3+ad897c4
prubenda-osp4-c9666-worker-0-7xbtr   Ready      worker            3h51m   v1.23.3+ad897c4
prubenda-osp4-c9666-worker-0-bglw4   Ready      worker            3h51m   v1.23.3+ad897c4
prubenda-osp4-c9666-worker-0-c7nrk   Ready      worker            3h51m   v1.23.3+ad897c4
prubenda-osp4-c9666-workload-mwg68   NotReady   worker,workload   17s     v1.23.3+ad897c4
```


```

NAME                                 STATUS   ROLES      AGE     VERSION
prubenda-osp4-c9666-infra-792hx      Ready    infra      8m      v1.23.3+ad897c4
prubenda-osp4-c9666-infra-9z827      Ready    infra      7m23s   v1.23.3+ad897c4
prubenda-osp4-c9666-infra-q5szq      Ready    infra      7m7s    v1.23.3+ad897c4
prubenda-osp4-c9666-master-0         Ready    master     4h13m   v1.23.3+ad897c4
prubenda-osp4-c9666-master-1         Ready    master     4h13m   v1.23.3+ad897c4
prubenda-osp4-c9666-master-2         Ready    master     4h13m   v1.23.3+ad897c4
prubenda-osp4-c9666-worker-0-7xbtr   Ready    worker     3h58m   v1.23.3+ad897c4
prubenda-osp4-c9666-worker-0-bglw4   Ready    worker     3h58m   v1.23.3+ad897c4
prubenda-osp4-c9666-worker-0-c7nrk   Ready    worker     3h58m   v1.23.3+ad897c4
prubenda-osp4-c9666-workload-mwg68   Ready    workload   6m55s   v1.23.3+ad897c4
```

**Pull request merged**
