### PR TITLE
Write to sheet extend request timeout

### PR DESCRIPTION
**Pull request by paigerube14**
Need to extend the request timeout of getting results from elastic search. May have to up this even more but increasing to 40 seconds as a start

### CODE REVIEW

**Comment by paigerube14** [comment]
See local test entry in the prow results google sheet

**Comment by paigerube14** [comment]
@svetsa-rh can you ptal as this is blocking for large scale clusters

**Comment by svetsa-rh** [comment]
@paigerube14 Is this the sheet where you mentioned local results? https://docs.google.com/spreadsheets/d/1cciTazgmvoD0YBdMuIQBRxyJnblVuczgbBL5xC8uGuI/edit#gid=138423700

When I clicked on 4.14 result, it opens prow link which is blank and nothing in the artifacts too.

**Comment by svetsa-rh** [comment]
Also, I see Harsha added a comment to https://issues.redhat.com/browse/PERFSCALE-2533 - didn't go look into details, but in case you missed it

**Comment by paigerube14** [comment]
@svetsa-rh these results are for cluster-density-v2 so you'll need to look at cluster-density-v2 tab 

I used the enviornment variables that were from [the prow run](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-aws-4.14-nightly-x86-ovnic-ocp-qe-perfscale-aws-ci-cdv2-test-252nodes-scale-ovnic/1708648158147383296/artifacts/ocp-qe-perfscale-aws-ci-cdv2-test-252nodes-scale-ovnic/openshift-qe-write-perfscale-results-cluster-density-v2/build-log.txt) to use when testing

The 4.14 tab is still a work in progress to be able to write all the results. This is a separate issue

**Comment by svetsa-rh** [comment]
/lgtm

given that the local run passed, let's merge this and see if we still need to increase prow write timeout as mentioned by Harsha

**Comment by paigerube14** [comment]
@svetsa-rh the issue with the timeout was specific to the elasticsearch connection not prow timeout. That's why I upped the request timeout in the elastic search call here 

```
Traceback (most recent call last):
  File "/tmp/XXXXXX-perfscale-ci/write_to_sheet/prow_write.py", line 77, in <module>
    write_prow_results_to_sheet()
  File "/tmp/XXXXXX-perfscale-ci/write_to_sheet/prow_write.py", line 71, in write_prow_results_to_sheet
    row.extend(write_helper.get_pod_latencies(uuid))
  File "/tmp/XXXXXX-perfscale-ci/write_to_sheet/write_helper.py", line 64, in get_pod_latencies
    pod_latencies_list = get_es_data.get_pod_latency_data(uuid)
  File "/tmp/XXXXXX-perfscale-ci/write_to_sheet/get_es_data.py", line 36, in get_pod_latency_data
    list_response = get_metadata_es("ripsaw-kube-burner", search_params)
  File "/tmp/XXXXXX-perfscale-ci/write_to_sheet/get_es_data.py", line 19, in get_metadata_es
    hits = update_es_uuid.es_search(search_params, index=index)
  File "/tmp/XXXXXX-perfscale-ci/write_to_sheet/update_es_uuid.py", line 26, in es_search
    **search_result = es.search(index=index, body={"query": {"bool": {"filter": filter_data}},  "size": size, "from": from_pos})**
  File "/tmp/venv_qe/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/tmp/venv_qe/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 1670, in search
    return self.transport.perform_request(
  File "/tmp/venv_qe/lib/python3.9/site-packages/elasticsearch/transport.py", line 415, in perform_request
    raise e
  File "/tmp/venv_qe/lib/python3.9/site-packages/elasticsearch/transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/tmp/venv_qe/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 263, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPSConnectionPool(host='search-XXXXXX-perf-scale-test-elk-hcm7wtsqpxy7xogbu72bor4uve.us-east-1.es.amazonaws.com', port=443): Read timed out. (read timeout=10))
```

**Pull request merged**
