### PR TITLE
Adding jenkinsfile for cluster checks

### PR DESCRIPTION
**Pull request by paigerube14**
Want to be able to add in cluster health checks using cerberus at the end of test runs, this is the first step

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/cerberus/109/

### CODE REVIEW

**Review by skordas — APPROVED** [review]
/lgtm

**Comment by paigerube14** [comment]
/assign @qiliRedHat 
/assign @mffiedler 

Please take a look at original PR to get cerberus integration into scale-ci. There are still some things not fully working on the cerberus side that I have been working on when time allows

**Pull request merged**
