### PR TITLE
network perf v2

### PR DESCRIPTION
**Pull request by paigerube14**
Adding network v2 to ignore uuid information

### CODE REVIEW

**Comment by paigerube14** [comment]
Passing job: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to_sheet/147/console

**Comment by paigerube14** [comment]
@SachinNinganure this helps make this runnable again. Going to add more functionality to get better grafana url for k8s net perf.

**Comment by paigerube14** [comment]
passing job here: https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to_sheet/150/console

**Comment by SachinNinganure** [comment]
I have run few tests for this; it is now going through of the past error; but in most of NPT-v2 my tests I am seeing null uuid and illegal_argument_exception
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/write-scale-ci-results/6126/console

https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/e2e-benchmarking-multibranch-pipeline/job/write-scale-ci-results/6125/console

**Comment by paigerube14** [comment]
@SachinNinganure you need to try on my branch to test this pr properly. Please look at links I've added

**Comment by SachinNinganure** [comment]
@paigerube14   correct!  I ran the test on your branch. I was just thinking if the "Scale-ci job ending status" does not matter . otherwise this looks fine.

**Comment by SachinNinganure** [comment]
https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/scale-ci/job/paige-e2e-multibranch/job/write-to_sheet/152/

/lgtm

**Pull request merged**
